name: test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: cache go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-codegen-

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: run lint
      run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: cache go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-codegen-

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: run tests
      run: make test